// Generated by CoffeeScript 2.7.0
var render_rotating_cube, renderer_class, ui_class;

renderer_class = class renderer_class {
  constructor(canvas, options) {
    this.canvas = canvas;
    this.gl = this.canvas.getContext("webgl2");
    if (!this.gl) {
      alert("unable to initialize webgl2.");
      return;
    }
    this.wire_program = webgl.create_program(this.gl, webgl.wire_vertex_shader_source, webgl.wire_fragment_shader_source);
    this.solid_program = webgl.create_program(this.gl, webgl.solid_vertex_shader_source, webgl.solid_fragment_shader_source);
    this.wire_vao = this.gl.createVertexArray();
    this.solid_vao = this.gl.createVertexArray();
    this.wire_position_buffer = this.gl.createBuffer();
    this.wire_index_buffer = this.gl.createBuffer();
    this.solid_position_buffer = this.gl.createBuffer();
    this.solid_color_buffer = this.gl.createBuffer();
    if (!(this.wire_program && this.solid_program && this.wire_vao && this.solid_vao && this.wire_position_buffer && this.wire_index_buffer && this.solid_position_buffer && this.solid_color_buffer)) {
      alert("unable to initialize required webgl resources.");
      return;
    }
    this.gl.clearColor(1, 1, 1, 1);
    this.gl.enable(this.gl.DEPTH_TEST);
    this.gl.depthFunc(this.gl.LEQUAL);
    this.gl.enable(this.gl.BLEND);
    this.gl.blendFunc(this.gl.SRC_ALPHA, this.gl.ONE_MINUS_SRC_ALPHA);
    this.configure_wire_pipeline();
    this.configure_solid_pipeline();
    this.scene = 0;
    this.options = 0;
    this.phase_time = 0;
    this.previous_frame_time = -1e18;
    this.frame_id = 0;
    this.set_options(options);
    this.on_frame = (time) => {
      if (this.options.refresh <= time - this.previous_frame_time) {
        this.previous_frame_time = time;
        this.draw(time);
      }
      return this.frame_id = requestAnimationFrame(this.on_frame);
    };
    this.frame_id = requestAnimationFrame(this.on_frame);
  }

  configure_wire_pipeline() {
    var gl, position_location;
    gl = this.gl;
    gl.bindVertexArray(this.wire_vao);
    gl.bindBuffer(gl.ARRAY_BUFFER, this.wire_position_buffer);
    position_location = gl.getAttribLocation(this.wire_program, "position");
    gl.enableVertexAttribArray(position_location);
    gl.vertexAttribPointer(position_location, 3, gl.FLOAT, false, 0, 0);
    gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, this.wire_index_buffer);
    return gl.bindVertexArray(null);
  }

  configure_solid_pipeline() {
    var color_location, gl, position_location;
    gl = this.gl;
    gl.bindVertexArray(this.solid_vao);
    gl.bindBuffer(gl.ARRAY_BUFFER, this.solid_position_buffer);
    position_location = gl.getAttribLocation(this.solid_program, "position");
    gl.enableVertexAttribArray(position_location);
    gl.vertexAttribPointer(position_location, 3, gl.FLOAT, false, 0, 0);
    gl.bindBuffer(gl.ARRAY_BUFFER, this.solid_color_buffer);
    color_location = gl.getAttribLocation(this.solid_program, "color");
    if (0 <= color_location) {
      gl.enableVertexAttribArray(color_location);
      gl.vertexAttribPointer(color_location, 4, gl.FLOAT, false, 0, 0);
    }
    return gl.bindVertexArray(null);
  }

  set_options(options) {
    this.options = {
      dimensions: options.dimensions,
      rotation_dimensions: options.rotation_dimensions.slice(),
      refresh: options.refresh,
      rotation_speed: options.rotation_speed,
      projection_depth: options.projection_depth,
      display_scale: options.display_scale,
      surface_alpha: options.surface_alpha,
      area_epsilon: options.area_epsilon,
      surfaces_enabled: options.surfaces_enabled,
      wireframe_enabled: options.wireframe_enabled
    };
    this.scene = new scene_class(this.options);
    this.upload_static_data();
    this.phase_time = performance.now();
    this.previous_frame_time = -1e18;
    return this.draw(this.phase_time);
  }

  upload_static_data() {
    var gl;
    gl = this.gl;
    gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, this.wire_index_buffer);
    gl.bufferData(gl.ELEMENT_ARRAY_BUFFER, this.scene.edge_indices, gl.STATIC_DRAW);
    gl.bindBuffer(gl.ARRAY_BUFFER, this.wire_position_buffer);
    gl.bufferData(gl.ARRAY_BUFFER, this.scene.projected_positions.byteLength, gl.DYNAMIC_DRAW);
    gl.bindBuffer(gl.ARRAY_BUFFER, this.solid_position_buffer);
    gl.bufferData(gl.ARRAY_BUFFER, this.scene.solid_positions.byteLength, gl.DYNAMIC_DRAW);
    gl.bindBuffer(gl.ARRAY_BUFFER, this.solid_color_buffer);
    return gl.bufferData(gl.ARRAY_BUFFER, this.scene.solid_colors, gl.STATIC_DRAW);
  }

  draw(time) {
    var gl;
    gl = this.gl;
    webgl.resize_canvas(this.canvas);
    gl.viewport(0, 0, this.canvas.width, this.canvas.height);
    this.scene.update_frame_data((time - this.phase_time) / 1000);
    gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);
    if (this.options.surfaces_enabled && this.scene.solid_positions.length) {
      gl.useProgram(this.solid_program);
      gl.bindVertexArray(this.solid_vao);
      gl.bindBuffer(gl.ARRAY_BUFFER, this.solid_position_buffer);
      gl.bufferSubData(gl.ARRAY_BUFFER, 0, this.scene.solid_positions);
      gl.drawArrays(gl.TRIANGLES, 0, this.scene.solid_positions.length / 3);
    }
    if (this.options.wireframe_enabled) {
      gl.useProgram(this.wire_program);
      gl.bindVertexArray(this.wire_vao);
      gl.bindBuffer(gl.ARRAY_BUFFER, this.wire_position_buffer);
      gl.bufferSubData(gl.ARRAY_BUFFER, 0, this.scene.projected_positions);
      gl.drawElements(gl.LINES, this.scene.edge_indices.length, gl.UNSIGNED_SHORT, 0);
    }
    return gl.bindVertexArray(null);
  }

  stop() {
    if (this.frame_id) {
      cancelAnimationFrame(this.frame_id);
    }
    return this.frame_id = 0;
  }

};

ui_class = class ui_class {
  constructor(draw) {
    this.on_dimensions_change = this.on_dimensions_change.bind(this);
    this.commit = this.commit.bind(this);
    this.canvas = document.getElementsByTagName("canvas")[0];
    this.warning_shown = false;
    this.dom = {};
    this.options = this.get_default_options();
    this.renderer = new renderer_class(this.canvas, this.options);
    this.build_controls();
    this.sync_rotation_plane_controls();
    this.bind_events();
    this.commit();
  }

  get_default_options() {
    var dimensions;
    dimensions = 4;
    return {
      dimensions: dimensions,
      rotation_dimensions: this.get_default_rotation_dimensions(dimensions),
      refresh: 16,
      rotation_speed: Math.PI * 0.08,
      projection_depth: 4,
      display_scale: 0.3,
      surface_alpha: 0.5,
      area_epsilon: 1e-7,
      surfaces_enabled: true,
      wireframe_enabled: true
    };
  }

  get_default_rotation_dimensions(dimensions) {
    return Array(dimensions * (dimensions - 1) / 2).fill(1);
  }

  normalize_rotation_dimensions(dimensions, rotation_dimensions) {
    var plane_count, result;
    plane_count = dimensions * (dimensions - 1) / 2;
    result = rotation_dimensions.slice(0, plane_count);
    while (result.length < plane_count) {
      result.push(1);
    }
    return result;
  }

  get_rotation_planes(dimensions) {
    var axis_a, axis_b, i, j, planes, ref, ref1;
    planes = [];
    for (axis_a = i = 1, ref = dimensions; (1 <= ref ? i <= ref : i >= ref); axis_a = 1 <= ref ? ++i : --i) {
      for (axis_b = j = 1, ref1 = dimensions; (1 <= ref1 ? j <= ref1 : j >= ref1); axis_b = 1 <= ref1 ? ++j : --j) {
        if (!(axis_a < axis_b)) {
          continue;
        }
        planes.push([axis_a, axis_b]);
      }
    }
    return planes;
  }

  label(text, content) {
    return crel("label", text, content);
  }

  read_number(input, fallback) {
    var value;
    value = parseFloat(input.value);
    if (isNaN(value)) {
      return fallback;
    } else {
      return value;
    }
  }

  build_controls() {
    var root;
    this.dom.dimensions = crel("input", {
      type: "number",
      min: "1",
      max: "7",
      value: this.options.dimensions
    });
    this.dom.rotation_speed = crel("input", {
      type: "number",
      min: "0",
      step: "0.01",
      value: this.options.rotation_speed / Math.PI
    });
    this.dom.refresh = crel("input", {
      type: "number",
      min: "1",
      step: "50",
      value: this.options.refresh
    });
    this.dom.projection_depth = crel("input", {
      type: "number",
      min: "1",
      step: "1",
      value: this.options.projection_depth
    });
    this.dom.display_scale = crel("input", {
      type: "number",
      min: "0.01",
      step: "0.1",
      value: this.options.display_scale
    });
    this.dom.surface_alpha = crel("input", {
      type: "number",
      min: "0",
      max: "1",
      step: "0.1",
      value: this.options.surface_alpha
    });
    this.dom.surfaces_enabled = crel("input", {
      type: "checkbox"
    });
    this.dom.surfaces_enabled.checked = this.options.surfaces_enabled;
    this.dom.wireframe_enabled = crel("input", {
      type: "checkbox"
    });
    this.dom.wireframe_enabled.checked = this.options.wireframe_enabled;
    this.dom.rotation_planes = crel("span");
    this.dom.controls_root = crel("div");
    root = this.dom.controls_root;
    root.appendChild(this.label("dimensions", this.dom.dimensions));
    root.appendChild(this.label("speed", this.dom.rotation_speed));
    //root.appendChild @label "refresh", @dom.refresh
    root.appendChild(this.label("depth", this.dom.projection_depth));
    root.appendChild(this.label("scale", this.dom.display_scale));
    root.appendChild(this.label("alpha", this.dom.surface_alpha));
    root.appendChild(this.label("surfaces", this.dom.surfaces_enabled));
    root.appendChild(this.label("wireframe", this.dom.wireframe_enabled));
    root.appendChild(crel("div", "rotation_planes", this.dom.rotation_planes));
    return document.getElementById("controls").appendChild(root);
  }

  bind_events() {
    this.dom.dimensions.addEventListener("change", this.on_dimensions_change);
    this.dom.rotation_speed.addEventListener("change", this.commit);
    this.dom.refresh.addEventListener("change", this.commit);
    this.dom.projection_depth.addEventListener("change", this.commit);
    this.dom.display_scale.addEventListener("change", this.commit);
    this.dom.surface_alpha.addEventListener("change", this.commit);
    this.dom.surfaces_enabled.addEventListener("change", this.commit);
    return this.dom.wireframe_enabled.addEventListener("change", this.commit);
  }

  on_dimensions_change() {
    var dimensions;
    dimensions = Math.floor(this.read_number(this.dom.dimensions, this.options.dimensions));
    dimensions = Math.max(1, dimensions);
    if (7 < dimensions) {
      alert("the current maximum number of dimensions is 7.");
      dimensions = 7;
    }
    if (!this.warning_shown && 6 <= dimensions) {
      alert("increasing dimensions can easily overload the browser.");
      this.warning_shown = true;
    }
    this.options.dimensions = dimensions;
    this.options.rotation_dimensions = this.normalize_rotation_dimensions(dimensions, this.options.rotation_dimensions);
    this.dom.dimensions.value = dimensions;
    this.sync_rotation_plane_controls();
    return this.commit();
  }

  sync_rotation_plane_controls() {
    var axis_a, axis_b, checkbox, i, len, plane, plane_index, results, rotation_planes, wrapper;
    rotation_planes = this.get_rotation_planes(this.options.dimensions);
    this.dom.rotation_planes.innerHTML = "";
    this.dom.rotation_dimension_inputs = [];
    results = [];
    for (plane_index = i = 0, len = rotation_planes.length; i < len; plane_index = ++i) {
      plane = rotation_planes[plane_index];
      [axis_a, axis_b] = plane;
      checkbox = crel("input", {
        type: "checkbox"
      });
      checkbox.checked = !!this.options.rotation_dimensions[plane_index];
      checkbox.addEventListener("change", this.commit);
      wrapper = crel("label", checkbox);
      this.dom.rotation_planes.appendChild(wrapper);
      results.push(this.dom.rotation_dimension_inputs.push(checkbox));
    }
    return results;
  }

  commit() {
    this.options.dimensions = Math.floor(this.read_number(this.dom.dimensions, this.options.dimensions));
    this.options.rotation_dimensions = this.dom.rotation_dimension_inputs.map(function(checkbox) {
      if (checkbox.checked) {
        return 1;
      } else {
        return 0;
      }
    });
    this.options.rotation_dimensions = this.normalize_rotation_dimensions(this.options.dimensions, this.options.rotation_dimensions);
    this.options.rotation_speed = Math.PI * this.read_number(this.dom.rotation_speed, this.options.rotation_speed / Math.PI);
    this.options.refresh = Math.max(1, Math.floor(this.read_number(this.dom.refresh, this.options.refresh)));
    this.options.projection_depth = Math.max(1, this.read_number(this.dom.projection_depth, this.options.projection_depth));
    this.options.display_scale = Math.max(0.01, this.read_number(this.dom.display_scale, this.options.display_scale));
    this.options.surface_alpha = Math.min(1, Math.max(0, this.read_number(this.dom.surface_alpha, this.options.surface_alpha)));
    this.options.surfaces_enabled = this.dom.surfaces_enabled.checked;
    this.options.wireframe_enabled = this.dom.wireframe_enabled.checked;
    return this.renderer.set_options(this.options);
  }

};

render_rotating_cube = function(options) {
  return new renderer_class(options.canvas, options);
};

if (typeof window !== "undefined" && window !== null) {
  window.renderer_class = renderer_class;
}

if (typeof window !== "undefined" && window !== null) {
  window.ui_class = ui_class;
}

if (typeof window !== "undefined" && window !== null) {
  window.render_rotating_cube = render_rotating_cube;
}
