// Generated by CoffeeScript 2.7.0
var scene_class, sph_ga, webgl;

if (typeof window === "undefined" || window === null) {
  sph_ga = require("./foreign/sph_ga.js");
}

scene_class = class scene_class {
  constructor(options) {
    this.set_options(options);
  }

  set_options(options) {
    this.dimensions = options.dimensions;
    this.rotation_dimensions = this.normalize_rotation_dimensions(options.rotation_dimensions);
    this.rotation_speed = options.rotation_speed;
    this.projection_depth = options.projection_depth;
    this.display_scale = options.display_scale;
    this.surface_alpha = options.surface_alpha;
    this.metric = this.make_metric();
    this.cga = new sph_ga(this.metric, {
      conformal: true
    });
    this.rotation_planes = this.get_rotation_planes();
    this.basis_ids = this.build_basis_ids();
    this.base_points = this.build_base_points();
    this.edge_indices = this.build_edge_indices();
    this.square_groups = this.build_square_groups();
    this.owner_colors = this.build_owner_colors();
    this.solid_colors = this.build_solid_colors();
    this.vertex_count = this.base_points.length;
    this.square_count = this.square_groups.square_count;
    this.projected_positions = new Float32Array(this.vertex_count * 3);
    this.solid_positions = new Float32Array(this.square_count * 18);
    return this.coord_buffer = new Float64Array(this.dimensions);
  }

  make_metric() {
    return Array(this.dimensions).fill(1);
  }

  get_rotation_planes() {
    var axis_a, axis_b, i, j, planes, ref, ref1;
    planes = [];
    for (axis_a = i = 1, ref = this.dimensions; (1 <= ref ? i <= ref : i >= ref); axis_a = 1 <= ref ? ++i : --i) {
      for (axis_b = j = 1, ref1 = this.dimensions; (1 <= ref1 ? j <= ref1 : j >= ref1); axis_b = 1 <= ref1 ? ++j : --j) {
        if (!(axis_a < axis_b)) {
          continue;
        }
        planes.push([axis_a, axis_b]);
      }
    }
    return planes;
  }

  normalize_rotation_dimensions(rotation_dimensions) {
    var plane_count, result;
    plane_count = this.dimensions * (this.dimensions - 1) / 2;
    result = rotation_dimensions.slice(0, plane_count);
    while (result.length < plane_count) {
      result.push(1);
    }
    return result;
  }

  build_basis_ids() {
    var basis_ids, dimension, i, ref;
    basis_ids = new Array(this.dimensions + 1);
    for (dimension = i = 1, ref = this.dimensions; (1 <= ref ? i <= ref : i >= ref); dimension = 1 <= ref ? ++i : --i) {
      basis_ids[dimension] = this.cga.id_from_indices([dimension]);
    }
    return basis_ids;
  }

  bits_to_coords(bits) {
    var ref;
    return (function() {
      var results = [];
      for (var i = 0, ref = this.dimensions; 0 <= ref ? i < ref : i > ref; 0 <= ref ? i++ : i--){ results.push(i); }
      return results;
    }).apply(this).map(function(dimension_index) {
      if (bits & (1 << dimension_index)) {
        return 1;
      } else {
        return -1;
      }
    });
  }

  build_base_points() {
    var base_points, coords, i, ref, vertex_count, vertex_index;
    vertex_count = 1 << this.dimensions;
    base_points = new Array(vertex_count);
    for (vertex_index = i = 0, ref = vertex_count; (0 <= ref ? i < ref : i > ref); vertex_index = 0 <= ref ? ++i : --i) {
      coords = this.bits_to_coords(vertex_index);
      base_points[vertex_index] = this.cga.point(coords);
    }
    return base_points;
  }

  build_edge_indices() {
    var dimension_index, edge_count, i, indices, j, ref, ref1, vertex, vertex_count, write_index;
    vertex_count = 1 << this.dimensions;
    edge_count = this.dimensions * (1 << (this.dimensions - 1));
    indices = new Uint16Array(edge_count * 2);
    write_index = 0;
    for (vertex = i = 0, ref = vertex_count; (0 <= ref ? i < ref : i > ref); vertex = 0 <= ref ? ++i : --i) {
      for (dimension_index = j = 0, ref1 = this.dimensions; (0 <= ref1 ? j < ref1 : j > ref1); dimension_index = 0 <= ref1 ? ++j : --j) {
        if (vertex & (1 << dimension_index)) {
          continue;
        }
        indices[write_index] = vertex;
        indices[write_index + 1] = vertex | (1 << dimension_index);
        write_index = write_index + 2;
      }
    }
    return indices;
  }

  build_square_groups() {
    var all_dimensions, assignment, assignment_count, base_vertex, dimension, dimension_a, dimension_b, first_index, fixed_dimension, fixed_value, i, j, k, l, len, len1, m, n, other_dimension, owner_count, owner_id, ref, ref1, ref2, ref3, ref4, ref5, ref6, remaining_dimensions, remaining_index, second_index, square_count, square_count_per_owner, square_index, square_owners, square_vertices, varying_dimensions, write_base;
    owner_count = this.dimensions * 2;
    if (this.dimensions < 2) {
      return {
        square_count: 0,
        square_vertices: new Uint16Array(0),
        square_owners: new Uint16Array(0),
        owner_count: owner_count
      };
    }
    square_count_per_owner = 2 < this.dimensions ? (this.dimensions - 1) * (this.dimensions - 2) * (1 << (this.dimensions - 3)) / 2 : 1;
    square_count = owner_count * square_count_per_owner;
    square_vertices = new Uint16Array(square_count * 4);
    square_owners = new Uint16Array(square_count);
    all_dimensions = (function() {
      var results = [];
      for (var i = 0, ref = this.dimensions; 0 <= ref ? i < ref : i > ref; 0 <= ref ? i++ : i--){ results.push(i); }
      return results;
    }).apply(this);
    square_index = 0;
    for (i = 0, len = all_dimensions.length; i < len; i++) {
      fixed_dimension = all_dimensions[i];
      varying_dimensions = all_dimensions.filter(function(dimension) {
        return dimension !== fixed_dimension;
      });
      ref1 = [0, 1];
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        fixed_value = ref1[j];
        owner_id = fixed_dimension * 2 + fixed_value;
        if (this.dimensions === 2) {
          base_vertex = 0;
          if (fixed_value) {
            base_vertex |= 1 << fixed_dimension;
          }
          other_dimension = varying_dimensions[0];
          write_base = square_index * 4;
          square_vertices[write_base] = base_vertex;
          square_vertices[write_base + 1] = base_vertex | (1 << other_dimension);
          square_vertices[write_base + 2] = base_vertex | (1 << other_dimension);
          square_vertices[write_base + 3] = base_vertex;
          square_owners[square_index] = owner_id;
          square_index = square_index + 1;
          continue;
        }
        for (first_index = k = 0, ref2 = varying_dimensions.length; (0 <= ref2 ? k < ref2 : k > ref2); first_index = 0 <= ref2 ? ++k : --k) {
          dimension_a = varying_dimensions[first_index];
          for (second_index = l = ref3 = first_index + 1, ref4 = varying_dimensions.length; (ref3 <= ref4 ? l < ref4 : l > ref4); second_index = ref3 <= ref4 ? ++l : --l) {
            dimension_b = varying_dimensions[second_index];
            remaining_dimensions = varying_dimensions.filter(function(dimension) {
              return dimension !== dimension_a && dimension !== dimension_b;
            });
            assignment_count = 1 << remaining_dimensions.length;
            for (assignment = m = 0, ref5 = assignment_count; (0 <= ref5 ? m < ref5 : m > ref5); assignment = 0 <= ref5 ? ++m : --m) {
              base_vertex = 0;
              if (fixed_value) {
                base_vertex |= 1 << fixed_dimension;
              }
              for (remaining_index = n = 0, ref6 = remaining_dimensions.length; (0 <= ref6 ? n < ref6 : n > ref6); remaining_index = 0 <= ref6 ? ++n : --n) {
                dimension = remaining_dimensions[remaining_index];
                if (assignment & (1 << remaining_index)) {
                  base_vertex |= 1 << dimension;
                }
              }
              write_base = square_index * 4;
              square_vertices[write_base] = base_vertex;
              square_vertices[write_base + 1] = base_vertex | (1 << dimension_a);
              square_vertices[write_base + 2] = base_vertex | (1 << dimension_a) | (1 << dimension_b);
              square_vertices[write_base + 3] = base_vertex | (1 << dimension_b);
              square_owners[square_index] = owner_id;
              square_index = square_index + 1;
            }
          }
        }
      }
    }
    return {
      square_count: square_index,
      square_vertices: square_vertices,
      square_owners: square_owners,
      owner_count: owner_count
    };
  }

  hsv_to_rgb(hue, saturation, value) {
    var fraction, p, q, sector, t;
    sector = Math.floor(hue * 6);
    fraction = hue * 6 - sector;
    p = value * (1 - saturation);
    q = value * (1 - fraction * saturation);
    t = value * (1 - (1 - fraction) * saturation);
    switch (sector % 6) {
      case 0:
        return [value, t, p];
      case 1:
        return [q, value, p];
      case 2:
        return [p, value, t];
      case 3:
        return [p, q, value];
      case 4:
        return [t, p, value];
      default:
        return [value, p, q];
    }
  }

  build_owner_colors() {
    var owner_count;
    owner_count = this.square_groups.owner_count;
    return (function() {
      var results = [];
      for (var i = 0; 0 <= owner_count ? i < owner_count : i > owner_count; 0 <= owner_count ? i++ : i--){ results.push(i); }
      return results;
    }).apply(this).map((owner_index) => {
      var blue, green, hue, red;
      hue = owner_index / Math.max(owner_count, 1);
      [red, green, blue] = this.hsv_to_rgb(hue, 0.85, 0.75);
      return [red, green, blue, this.surface_alpha];
    });
  }

  build_solid_colors() {
    var color, i, j, len, owner_id, solid_colors, square_index, square_owners, vertex_base, vertex_index, write_base;
    square_owners = this.square_groups.square_owners;
    solid_colors = new Float32Array(square_owners.length * 24);
    for (square_index = i = 0, len = square_owners.length; i < len; square_index = ++i) {
      owner_id = square_owners[square_index];
      color = this.owner_colors[owner_id];
      write_base = square_index * 24;
      for (vertex_index = j = 0; j < 6; vertex_index = ++j) {
        vertex_base = write_base + vertex_index * 4;
        solid_colors[vertex_base] = color[0];
        solid_colors[vertex_base + 1] = color[1];
        solid_colors[vertex_base + 2] = color[2];
        solid_colors[vertex_base + 3] = color[3];
      }
    }
    return solid_colors;
  }

  build_rotor_total(time_seconds) {
    var axis_a, axis_b, enabled, half_angle, i, len, plane_index, ref, rotor_component, rotor_total;
    rotor_total = this.cga.s(1);
    ref = this.rotation_dimensions;
    for (plane_index = i = 0, len = ref.length; i < len; plane_index = ++i) {
      enabled = ref[plane_index];
      if (!enabled) {
        continue;
      }
      [axis_a, axis_b] = this.rotation_planes[plane_index];
      half_angle = time_seconds * this.rotation_speed * 0.5;
      rotor_component = this.cga.add(this.cga.s(Math.cos(half_angle)), this.cga.mv([[[axis_a, axis_b], -Math.sin(half_angle)]]));
      rotor_total = this.cga.gp(rotor_total, rotor_component);
    }
    return rotor_total;
  }

  extract_coords(point_mv) {
    var blade, dimension, i, ref, results;
    results = [];
    for (dimension = i = 1, ref = this.dimensions; (1 <= ref ? i <= ref : i >= ref); dimension = 1 <= ref ? ++i : --i) {
      blade = this.cga.get(point_mv, this.basis_ids[dimension]);
      results.push(this.coord_buffer[dimension - 1] = blade ? this.cga.blade_coeff(blade) : 0);
    }
    return results;
  }

  project_coords_to_3d() {
    var coord_index, current_dimension, i, j, ref, ref1, scale, x, y, z;
    for (current_dimension = i = ref = this.dimensions; i >= 4; current_dimension = i += -1) {
      scale = this.projection_depth / (this.projection_depth - this.coord_buffer[current_dimension - 1]);
      for (coord_index = j = 0, ref1 = current_dimension - 1; (0 <= ref1 ? j < ref1 : j > ref1); coord_index = 0 <= ref1 ? ++j : --j) {
        this.coord_buffer[coord_index] = this.coord_buffer[coord_index] * scale;
      }
    }
    x = 0 < this.dimensions ? this.coord_buffer[0] * this.display_scale : 0;
    y = 1 < this.dimensions ? this.coord_buffer[1] * this.display_scale : 0;
    z = 2 < this.dimensions ? this.coord_buffer[2] * this.display_scale : 0;
    return [x, y, z];
  }

  update_projected_positions(time_seconds) {
    var i, len, point_mv, ref, results, rotated_point, rotor_total, vertex_index, write_base, x, y, z;
    rotor_total = this.build_rotor_total(time_seconds);
    ref = this.base_points;
    results = [];
    for (vertex_index = i = 0, len = ref.length; i < len; vertex_index = ++i) {
      point_mv = ref[vertex_index];
      rotated_point = this.cga.sp(rotor_total, point_mv);
      this.extract_coords(rotated_point);
      [x, y, z] = this.project_coords_to_3d();
      write_base = vertex_index * 3;
      this.projected_positions[write_base] = x;
      this.projected_positions[write_base + 1] = y;
      results.push(this.projected_positions[write_base + 2] = z);
    }
    return results;
  }

  write_triangle_3d(target, write_base, ax, ay, az, bx, by_, bz, cx, cy, cz) {
    target[write_base] = ax;
    target[write_base + 1] = ay;
    target[write_base + 2] = az;
    target[write_base + 3] = bx;
    target[write_base + 4] = by_;
    target[write_base + 5] = bz;
    target[write_base + 6] = cx;
    target[write_base + 7] = cy;
    return target[write_base + 8] = cz;
  }

  update_solid_positions() {
    var ax, ay, az, bx, by_, bz, cx, cy, cz, dx, dy, dz, i, ref, results, source, source_base, square_index, square_vertices, target, target_base, vertex_a, vertex_b, vertex_c, vertex_d;
    source = this.projected_positions;
    target = this.solid_positions;
    square_vertices = this.square_groups.square_vertices;
    results = [];
    for (square_index = i = 0, ref = this.square_count; (0 <= ref ? i < ref : i > ref); square_index = 0 <= ref ? ++i : --i) {
      source_base = square_index * 4;
      target_base = square_index * 18;
      vertex_a = square_vertices[source_base] * 3;
      vertex_b = square_vertices[source_base + 1] * 3;
      vertex_c = square_vertices[source_base + 2] * 3;
      vertex_d = square_vertices[source_base + 3] * 3;
      ax = source[vertex_a];
      ay = source[vertex_a + 1];
      az = source[vertex_a + 2];
      bx = source[vertex_b];
      by_ = source[vertex_b + 1];
      bz = source[vertex_b + 2];
      cx = source[vertex_c];
      cy = source[vertex_c + 1];
      cz = source[vertex_c + 2];
      dx = source[vertex_d];
      dy = source[vertex_d + 1];
      dz = source[vertex_d + 2];
      this.write_triangle_3d(target, target_base, ax, ay, az, bx, by_, bz, cx, cy, cz);
      results.push(this.write_triangle_3d(target, target_base + 9, ax, ay, az, cx, cy, cz, dx, dy, dz));
    }
    return results;
  }

  update_frame_data(time_seconds) {
    this.update_projected_positions(time_seconds);
    return this.update_solid_positions();
  }

};

webgl = {
  wire_vertex_shader_source: `#version 300 es
precision highp float;
in vec3 position;
void main() {
  gl_Position = vec4(position, 1.0);
}`,
  wire_fragment_shader_source: `#version 300 es
precision highp float;
out vec4 fragment_color;
void main() {
  fragment_color = vec4(0.08, 0.08, 0.08, 1.0);
}`,
  solid_vertex_shader_source: `#version 300 es
precision highp float;
in vec3 position;
in vec4 color;
out vec4 vertex_color;
void main() {
  gl_Position = vec4(position, 1.0);
  vertex_color = color;
}`,
  solid_fragment_shader_source: `#version 300 es
precision highp float;
in vec4 vertex_color;
out vec4 fragment_color;
void main() {
  fragment_color = vertex_color;
}`,
  create_shader: function(gl, type_name, source) {
    var shader;
    shader = gl.createShader(gl[type_name]);
    gl.shaderSource(shader, source);
    gl.compileShader(shader);
    if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
      console.error(gl.getShaderInfoLog(shader));
      gl.deleteShader(shader);
      return 0;
    }
    return shader;
  },
  create_program: function(gl, vertex_source, fragment_source) {
    var fragment_shader, program, vertex_shader;
    vertex_shader = this.create_shader(gl, "VERTEX_SHADER", vertex_source);
    fragment_shader = this.create_shader(gl, "FRAGMENT_SHADER", fragment_source);
    if (!(vertex_shader && fragment_shader)) {
      return 0;
    }
    program = gl.createProgram();
    gl.attachShader(program, vertex_shader);
    gl.attachShader(program, fragment_shader);
    gl.linkProgram(program);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
      console.error(gl.getProgramInfoLog(program));
      gl.deleteProgram(program);
      return 0;
    }
    return program;
  },
  resize_canvas: function(canvas) {
    var height, ratio, width;
    ratio = window.devicePixelRatio || 1;
    width = Math.floor(canvas.clientWidth * ratio);
    height = Math.floor(canvas.clientHeight * ratio);
    if (canvas.width !== width || canvas.height !== height) {
      canvas.width = width;
      return canvas.height = height;
    }
  }
};

if (typeof window !== "undefined" && window !== null) {
  window.scene_class = scene_class;
}

if (typeof window !== "undefined" && window !== null) {
  window.webgl = webgl;
}
